# syntax=docker/dockerfile:1
ARG NODE_VERSION=20.19.0
################################################################################
# Use node image for base image for all stages.
FROM node:${NODE_VERSION}-alpine as base
# Copy the timezone file to /etc/localtime
RUN apk add --no-cache tzdata 
ENV TZ=Asia/Dhaka
RUN cp /usr/share/zoneinfo/Asia/Dhaka /etc/localtime
# Define health check status parameters.
RUN apk add --no-cache curl

# Set working directory for all build stages.
WORKDIR /usr/src/app

# Copy the rest of the source files into the image.
COPY . .
RUN npm install --force
# Run the build script.
RUN yarn run build
#Change the ownership
USER root
RUN chown -R node:node /usr/src/app/
# Run the application as a non-root user.
USER node
# Expose the port that the application listens on.
EXPOSE 3004
# Run the application.
CMD ["yarn", "start"]
