CREATE TABLE `pos_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `sbu_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `ProductName` VARCHAR(255) NULL,
  `ProductImage` VARCHAR(200) NULL,
  `component` TEXT NULL,
  `description` TEXT NULL,
  `notes` VARCHAR(255) NULL,
  `menu_type` VARCHAR(25) NULL,
  `product_vat` DECIMAL(10,3) NOT NULL DEFAULT 0,
  `special` INT NOT NULL DEFAULT 0,
  `Offer_rate` INT NOT NULL DEFAULT 0 COMMENT '1=offer rate',
  `offer_is_available` INT NOT NULL DEFAULT 0 COMMENT '1=offer available,0=No Offer',
  `offer_start_date` DATE NULL,
  `offer_end_date` DATE NULL,
  `Position` INT NULL,
  `kitchen_id` INT NOT NULL,
  `is_group` INT NULL,
  `is_custom_qty` INT NOT NULL DEFAULT 0,
  `cooked_time` TIME NOT NULL DEFAULT '00:00:00',
  `is_active` TINYINT NULL,
  `customer_note` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted_by` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_pos_products_category` FOREIGN KEY (`category_id`) REFERENCES `pos_categories` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
